# file: roles/install-postgresql-on-el6/tasks/databases.yml -- manage databases

- name: "Stage 4: add databases"
  postgresql_db:
    state: present
    name: "{{ item.name }}"
    template: "{{ item.template }}"
    encoding: "{{ item.encoding }}"
    lc_collate: "{{ item.collate }}"
    lc_ctype: "{{ item.ctype }}"
    owner: "{{ item.owner }}"
  with_items: postgresql_databases
  when: postgresql_databases|length > 0
  register: db_create_result

# todo: this is always changed
- name: Import initial database data
  command: "pg_restore -d{{ item.item.name }} -U{{postgresql_admin_user}} {{ item.item.import_data }}"
  when: item.changed and item.item.import_data is defined
  with_items: db_create_result.results

- name: "Stage: 4: add extensions"
  command: "psql {{ item[0].name }} -U{{postgresql_admin_user}} -c 'CREATE EXTENSION IF NOT EXISTS {{ item[1] }}'"
  with_nested:
    - postgresql_databases
    - postgresql_extensions
  when: postgresql_contrib and postgresql_extensions|length > 0 and postgresql_version != '8.4'
